# Generated by Django 4.1.3 on 2022-12-14 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('pays', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'PAYS',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('numproduit', models.TextField(db_column='numProduit', primary_key=True, serialize=False)),
                ('nomproduit', models.TextField(blank=True, db_column='nomProduit', null=True)),
            ],
            options={
                'db_table': 'PRODUIT',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('numfacture', models.TextField(db_column='numFacture', primary_key=True, serialize=False)),
                ('dateachat', models.DateField(blank=True, db_column='dateAchat', null=True)),
                ('pays', models.ForeignKey(blank=True, db_column='pays', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='analyse.pays')),
            ],
            options={
                'db_table': 'FACTURE',
            },
        ),
        migrations.CreateModel(
            name='Dtlfact',
            fields=[
                ('iddtfact', models.AutoField(db_column='idDtFact', primary_key=True, serialize=False)),
                ('qte', models.IntegerField(blank=True, null=True)),
                ('numfacture', models.ForeignKey(blank=True, db_column='numFacture', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='analyse.facture')),
                ('numproduit', models.ForeignKey(blank=True, db_column='numProduit', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='analyse.produit')),
            ],
            options={
                'db_table': 'DTLFACT',
            },
        ),
    ]
