# Generated by Django 4.1.3 on 2022-12-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dtlfact',
            fields=[
                ('iddtfact', models.AutoField(db_column='idDtFact', primary_key=True, serialize=False)),
                ('qte', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DTLFACT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('numfacture', models.TextField(db_column='numFacture', primary_key=True, serialize=False)),
                ('datefact', models.DateField(blank=True, db_column='dateFact', null=True)),
            ],
            options={
                'db_table': 'FACTURE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('pays', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'PAYS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('numproduit', models.TextField(db_column='numProduit', primary_key=True, serialize=False)),
                ('nomproduit', models.TextField(blank=True, db_column='nomProduit', null=True)),
                ('pu', models.TextField(blank=True, db_column='PU', null=True)),
            ],
            options={
                'db_table': 'PRODUIT',
                'managed': False,
            },
        ),
    ]
