# Generated by Django 4.1.3 on 2022-12-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='pu',
            field=models.TextField(blank=True, db_column='PU', null=True),
        ),
    ]
